### ISSUE TITLE
Keyboard will not appear when tapping "Enter custom token" in Safari/Chrome on Apple touchscreen devices.

### ISSUE THREAD

**Issue by ConfluxJL** [jimmyl0l3c/cfg_share_links#91] opened 2022-12-12 08:54 UTC
![Enter custom token](https://user-images.githubusercontent.com/120368067/206998909-c45d1ea6-2be9-45be-be9b-4744377f1707.jpg)

Nextcloud 25.0.1
Configurable Share Links 3.0.1

When tapping "Enter custom token" on the web application with a touchscreen, the keyboard does not appear.

I have tested this with an iPhone 14 Pro Max (iOS 16.1.1) and an iPad Air Gen 4 (iPad OS 15.7). Using both the Safari and Chrome apps. Unable to create "Custom public link" in any of those scenarios.

Tapping "Name, Email, or Federated Cloud ID ..." does function properly and will bring up the keyboard. Tapping back on "Enter custom token" causes the keyboard to be dismissed, thereby making it impossible to enter custom token and giving "Invalid token error" when tapping plus button.

**Comment by jimmyl0l3c** [comment] 2022-12-12 15:23
Hi, 
thank you for reporting this issue. I was able to find the cause of this and I will try to fix it soon.

In the meantime, one way I found to create the link on mobile device is to tap on the "Name, Email, or Federated Cloud ID ..." input and then switch to next input (tap the arrow button equivalent of pressing Tab key).

**Comment by jimmyl0l3c** [comment] 2022-12-12 17:07
It should be fixed in release [3.0.2](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v3.0.2).

**Closed** 2022-12-14 16:45 UTC
Labels: bug
