### ISSUE TITLE
Custom share token are not deleted if the shared file is deleted

### ISSUE THREAD

**Issue by Practicalbutterfly5** [jimmyl0l3c/cfg_share_links#30] opened 2022-03-17 03:44 UTC
Steps to reproduce:
1 Create a custom link
2 Delete the shared file
3 Try to create a new custom link with same custom token

Result:
Unable to create link as it already exist 

Expected:
I should be allowed to create a new custom link with same custom token after the file was deleted.

**Comment by jimmyl0l3c** [comment] 2022-03-17 08:56
Hi,
thanks for reporting this issue.

I briefly tested it and found out that even the random generated tokens are not deleted when the file is deleted, which makes sense for the random tokens. 

I'll look into it.

**Comment by jimmyl0l3c** [comment] 2022-03-26 16:33
The issue is fixed in [version 1.2.0](https://github.com/jimmyl0l3c/cfg_share_links/releases/tag/v1.2.0).

When deleting file/folder that is shared with custom token, the custom shares are removed and the tokens can be used again. This works only with custom shares created/updated with version 1.2.0 (or later).

If you have custom tokens in database that were created using previous versions and cannot be used now, there is a new option to solve that. 
Navigate to **Settings > Administration > Configurable Share Links** and turn on the option: **Delete shares of deleted files during token checks (when creating/updating share)**.
Now if you try to create(/update) new custom share with token that was used for sharing deleted file/folder, the previous share will be deleted during token checks (when checking if the token is unique).

**Closed** 2022-03-26 16:35 UTC
Labels: bug
